### ISSUE TITLE
What is happening? (Mobs not stacking, forge 1.20.1 latest version)

### ISSUE THREAD

**Issue by Looxond** [frikinjay/mob-stacker#6]
https://github.com/user-attachments/assets/190422ff-730c-47e8-bc3e-ba8a6a0157dc

Logs: https://mclo.gs/z9f5BdW

(Yes the tooltip doesnt show up, killing them acts as if i only killed one)

**Comment by hideki2k02** [comment]
Same thing happening on my end, but I'm using Fabric.

Minecraft Version: 1.20.1
MobStacker Version: 1.0.8
Almanac Version: 1.0.2
Cupboard Version: 2.7

**Comment by frikinjay** [comment]
Fixed in 1.0.9
